### ISSUE TITLE
[JetpackCompose] Improvements for Jetpack Compose App

### ISSUE THREAD

**Issue by PatilShreyas** [PatilShreyas/NotyKT#117]
- [x] [#117-1] Clear back stack after successful login/signup _(**Issue:** When back navigation is pressed from Notes Screen, it tries to go back for sign in)_.  ***[Fixed by #135]***
- [ ] [#117-2] Add transitions while navigating among different screens _(As present in simple app module)_.
- [x] [#117-3] Add About screen for details regarding app _(As present in simple app module)_. ***[Fixed by #135]***
- [x] [#117-4] Validate text fields before performing actions with `ViewModel`. ***[Fixed by #135]***
- [x] [#117-5] Create re-usable **Composable** components to reduce repetitive code.

**Comment by PatilShreyas** [comment]
As of now, just #117-2 is pending and AFAIK, it's not supported officially so closing this issue and will create separate issue for it.
